#!/bin/bash

# for icons https://www.nerdfonts.com/cheat-sheet

sketchybar --add event aerospace_workspace_change

source "$CONFIG_DIR/colors.sh"

ITEM_DIR="$CONFIG_DIR/items"
PLUGIN_DIR="$CONFIG_DIR/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

FONT="Hack Nerd Font"

CLOCK_COLOUR="0xfff6d6ff"
CPU_COLOUR="0xffa1ffbd"
RAM_COLOUR="0xffadebff"
BATTER_COLOUR="0xfffff1a1"

bar=(
  height=32
  blur_radius=30
  position=top
  sticky=off
  padding_left=10
  padding_right=10
  color=0x00000000
  notch_width=190
)
sketchybar --bar "${bar[@]}"

default=(
  updates=when_shown
  icon.font="$FONT:Bold:17.0"
  icon.font="$FONT:Mono:15.0"
  icon.color=$WHITE
  label.font="SF Pro:Bold:12.0"
  label.color=$WHITE
  background.corner_radius=8
  background.height=26
  background.color="$TRANSPARENT"
  padding_left=3
  padding_right=3
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
sketchybar \
  --add item front_app q \
  --set front_app icon.font="sketchybar-app-font:Regular:15.0" \
                  script="$PLUGIN_DIR/front_app.sh" \
                  background.border_color=$BORDER \
                  background.border_width=1 \
  --subscribe front_app front_app_switched

sketchybar --add event aerospace_workspace_change

sketchybar \
  --add event spotify_change $SPOTIFY_EVENT \
  --add item spotify left \
  --set spotify \
        icon=":spotify:"  \
        icon.font="sketchybar-app-font:Regular:15.0" \
        background.border_color=$BORDER \
        background.border_width=1 \
        icon.y_offset=1 \
        script="$PLUGIN_DIR/spotify.sh" \
        align=left \
  --subscribe spotify spotify_change mouse.clicked

# -- Right Side Items --
sketchybar \
  --add item clock right \
  --set clock icon="􀐬" \
              icon.color=$CLOCK_COLOUR \
              update_freq=10 \
              background.border_color=$BORDER \
              background.border_width=1 \
              script="$PLUGIN_DIR/clock.sh"

sketchybar \
  --add item weather right \
  --set weather icon="􀇃"  \
                update_freq=600 \
                background.border_color=$BORDER \
                background.border_width=1 \
                script="$PLUGIN_DIR/weather.sh"

source $ITEM_DIR/battery.sh

sketchybar \
  --add item cpu right \
  --set cpu update_freq=2 \
            icon="􀫥" \
            icon.font="sketchybar-app-font:Regular:15.0" \
            icon.color=$CPU_COLOUR \
            background.border_color=$BORDER \
            background.border_width=1 \
            script="$PLUGIN_DIR/cpu.sh" \
            label.align=right \
            label.width=45 \
            align=right


sketchybar \
  --add item ram right \
  --set ram update_freq=2 \
            icon="􀫦" \
            icon.font="sketchybar-app-font:Regular:15.0" \
            icon.color=$RAM_COLOUR \
            background.border_color=$BORDER \
            background.border_width=1 \
            script="$PLUGIN_DIR/ram.sh" \
            label.align=right \
            label.width=59 \
            align=left

sketchybar \
  --add item teams right \
  --set teams icon.font="sketchybar-app-font:Mono:15.0" \
              update_freq=5 \
              script="$PLUGIN_DIR/notifications.sh" \
              click_script="open -a 'Microsoft Teams'" \
              icon="󰊻" \
              background.border_color=$BORDER \
              background.border_width=1 \
  --subscribe teams system_woke

sketchybar --update
